# Generated by Django 2.2.10 on 2020-06-05 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200605_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 12, 57, 24, 606846)),
        ),
    ]
