# Generated by Django 2.1.1 on 2020-05-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='square_feet',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
